/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HW1;

import com.google.gson.Gson;

import java.util.Map;

public class App{
    public static void main(String[] args) {
        Map<String, String> human = Map.of(
                "name", "Igor",
                "lastname", "Petrenko");

        System.out.println(new Gson().toJson(human));
    }
}
